const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const user_account_schema = new Schema({
    //account id = mongo default _id
    //creation date + time = autogenerated mongodb date + time
    user_username: {
        type: String,
        require: true
    },
    user_password: {
        type: String,
        require: true
    },
    balance: {
        type: number,
    }
}, {timestamps: true});
module.exports = mongoose.model("user_account", user_account_schema);